### ISSUE TITLE
Covers are incorrect displayed in HomeKit

### ISSUE THREAD

**Issue by jortberends** [ualex73/slide#1]
First of all, thanks for creating this component!

After adding my Slides to HomeKit via this HomeAssistant component, they are reflecting the status incorrect in HomeKit.
When the curtains are closed, HomeKit will tell me they are open, and vise versa.
Asking Siri to "open" the curtains will close them and vise versa.
The status is correct displayed in the Slide.go app

Could it be that HomeAssistant and Slide are treating the position differently?
Like Slide thinks:
0=closed
1=open
While HA treats it like:
100=closed
0=open

**Comment by ualex73** [comment]
Yes, at this moment 1.0 (100%) is treated as "closed" and 0.0 (0%) is treated as open.

Only do you know which state/variable HA is used for the HomeKit. I am returning the "state" == "CLOSED" / "OPEN" / etc ... so thats should be correct. I am guessing HomeKit is using "current_cover_position" function to determine it is open/close (that one returns 0 - 100%).

I could introduce an cover invert parameter (like is done for some other cover components). I will code that soon and let you know.

**Comment by jortberends** [comment]
@ualex73 i think you're right about the current_cover_position
Looking at: [HMCharacteristicTypeCurrentPosition](https://developer.apple.com/documentation/homekit/hmcharacteristictypecurrentposition) it states:
> The corresponding value is an integer percentage. A value of 0 indicates a door or window is fully closed, or that awnings or shades permit the least possible light. A value of 100 indicates the opposite.

So i guess we need to invert the parameter indeed.

**Comment by ualex73** [comment]
Can you try the new master branch of the slide code? It has a new configuration item called "invert_position: true" ... Then it will invert the position so 0 -> 100, 100 -> 0, 5 -> 95, 80 -> 20, etc.

**Comment by ualex73** [comment]
This is going into HA 0.109, so I will close this one it in 1-2 weeks.

**Comment by jortberends** [comment]
I can confirm that with HA 0.109 it is working as expected!
Thanks for your work!

**Comment by ualex73** [comment]
Perfect 👍 BTW - The Local API is also available as custom component.
