### ISSUE TITLE
Slides not working

### ISSUE THREAD

**Issue by PscNed74** [ualex73/slide#10]
HI 

I have 2 slides.  I am using the local api (as the cloud version is not working in Home Assistant anymore). One is configured as:
- platform: slide
  host: <ipnumber>
  password: <password>
  api_version: 1

This one is working fine. As soon as I add another slide with the same config but another password and ip number ofcourse, this new slide is not working. WHen trying to open this using HomeAssistant, I get the following error: 

RES-L26: API=http://<ip>/rpc/Slide.SetPos, type=POST, HTTPCode=500, Data={"code":-1,"message":"{\"response\": \"bad request\"}"}

It seems like I have two slides with different API versions. When I add the api_version: 2 to the second slide. Initialisation seems to be working but when I try to open and close, nothing happens.

Hopefully you can fix this issue as up until now everything was working perfectly!

**Comment by mschut** [comment]
Hi all,

I think I am experiencing the same results. I have three slides which I would like to connect through the local api. With api version 1 I won't get any reponse, so I switched to api version 2. This works like a charm, although so it seems. The slides are visible, the correct position is showed, I can calibrate them. However, controlling them is not working. Funny enough I still can control them through the Slide app as well. This will result in the correct position showed by the local slides in HA. But controlling is just not working.

**Comment by vBrolin** [comment]
Got the same issue.
Just installed an old Kickstarter Slide I've been collecting dust since I got it.
Worked fine on API 1 until the device updated to the new firmware.
It wont respond at all when set to API 1 one, which makes sense, but set to API 2 I can only see the position, not change it.
