### ISSUE TITLE
Slide(s) unavailable after HA Reboot mainly after HA update

### ISSUE THREAD

**Issue by MuadDib007** [ualex73/slide#14]
Hello,

Some time (Especially when updating HA to a newer version) one or both of my slides show as unavailable.
The only solution at the moment is to restart HA again (Either reload only HA or reboot the entire system, both seem to help).

Even after this reboot sometimes this only fixes one of the Slides and I need to perform another reboot.
With any other integration I would simply invoke a reload for the respective integration to solve the issue.
However I do not know how to do this as I cannot find the ID of the integration via the GUI.

Any help would be appreciated (Either a fix for the unavailability or assistance in reload the integration)

**Comment by hugo-leij** [comment]
Hi,

I'm experiencing the same issues. Additionally, if the slide loses WiFi signal or encounters another issue, it becomes problematic. That's why I switched back to the cloud version, but that will only work for a few more weeks (I guess).

I was considering placing a Fibaro wall plug between it to reset the power of the slide, but I'm not sure if that will help. Unfortunately, I can't test it at the moment because I’m on holiday. Do you think that will work or must it be a restart / reload?

**Comment by MuadDib007** [comment]
In my case I do also find them unavailable and disconnected from the wifi
from time to time (mostly happens when I have made changes to the wifi)
therefore that is a non issue for me, although better handling of lost wifi
connectivity would be a nice improvement.

When the issue is caused by wifi interruption, power cycling the Slide
solves the issue so in my opinion that is a different issue.

When the Slide is shown unavailable at boot a reboot of HA is needed to
solve the issue.

I have observed this issue also with EspSomfyRTS and they have solved this
in a recent update.
In addition as their integration is visible in the gui, you can restart
that via automation if it stays unavailable for too long.

Op vr 17 mei 2024 03:47 schreef hugo-leij ***@***.***>:

**Comment by ualex73** [comment]
I will check if we can call reload of the integration/slide. Maybe a retry is an option too (but also here, I need to investigate - it is a long time I wrote the code)

**Comment by MuadDib007** [comment]
With version 1.2 and 1.3 my slides are not working.
Keep getting the following errors:

Deze fout is ontstaan door een aangepaste integratie.

Logger: goslideapi.goslideapi
Bron: custom_components/slide/cover.py:62
integratie: Slide
Eerst voorgekomen: 20:16:14 (2 gebeurtenissen)
Laatst gelogd: 20:16:15

Failed request Local API v2. HTTPCode=401

Followed by:

Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.slide.cover
Bron: custom_components/slide/cover.py:79
integratie: Slide
Eerst voorgekomen: 20:16:14 (2 gebeurtenissen)
Laatst gelogd: 20:16:15

Unable to setup Slide Local '192.168.178.76'
Unable to setup Slide Local '192.168.178.79'

I have tried to set the Slides to cloud and back to local API again.
Slide app is working fine with them.
Version 1.1b1 is still working with previously mentioned incidental issues.

**Comment by ualex73** [comment]
Can you try with api v1?

like:
cover:
  - platform: slide
    host: 192.168.1.1
    password: 12345678
    api_version: 1

**Comment by MuadDib007** [comment]
I have tried and I get a different error message now:

Logger: homeassistant.components.cover
Bron: helpers/entity_platform.py:356
integratie: Raambekleding (documentatie, problemen)
Eerst voorgekomen: 09:52:41 (2 gebeurtenissen)
Laatst gelogd: 09:52:41

Error while setting up slide platform for cover
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py",
line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/slide/cover.py", line 62, in
async_setup_platform
    slide = await
hass.data[DOMAIN][API_LOCAL].slide_info(config.get(CONF_HOST))

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/goslideapi/goslideapi.py",
line 688, in slide_info
    result = await self._request(
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/goslideapi/goslideapi.py",
line 628, in _request
    respstatus, resptext = await self._dorequest(
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/goslideapi/goslideapi.py",
line 575, in _dorequest
    raise ClientConnectionError(str(err)) from None
goslideapi.goslideapi.ClientConnectionError: Cannot connect to host
192.168.178.76:80 ssl:default [Connect call failed ('192.168.178.76', 80)]

I will try to keep my slides connected to the cloud upcoming night hoping
they will receive a firmware update enabling V2 as that is a better more
future proof fix I presume.

Op za 18 mei 2024 22:05 schreef Alexander ***@***.***>:

**Comment by ualex73** [comment]
If you disabled the local api again, that then means the "slide" integration cannot connect your ip 192.168.178.76 on port 80.

I test myself as follows if the port 80 is available. Following command, port is listening - so local api should work/respond:
```telnet 192.168.1.11 80
Trying 192.168.1.11...
Connected to 192.168.1.11.
Escape character is '^]'.
```

When no local api can work:
```
telnet 192.168.1.11 80
Trying 192.168.1.11...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by MuadDib007** [comment]
Sorry for the confusion, but during testing the Local API was active.

It seems fixed now after performing the following steps:

Leave Slide on cloud overnight.
Set slide to local API again.
Remove Slide Component from HA
Install Slide Component 1.3
Full system reboot of HA.

Bot Slides are now available and controllable from HA.

Also at the moment available after the first boot of HA.
Let's see what happens with future HA updates.

Thank you so far for your support.

Op zo 19 mei 2024 11:32 schreef Alexander ***@***.***>:

**Comment by ualex73** [comment]
Thanks for the update, so we can close this ticket.
