### ISSUE TITLE
Add support for speed control feature

### ISSUE THREAD

**Issue by RIP21** [ualex73/slide#3]
Hi there! I'm using this integration through the Home Assistant, but I guess the fastest way to notify would be to write here too :)

I just opened a discussion on the Home Assistant feature forum here
https://community.home-assistant.io/t/slide-curtains-add-slide-speed-control-into-integration/270819 

Here is the quote:
> Here is the new feature that is added which will be awesome to control from Home Assistant.
> https://support.slide.store/article/336-slide-speed-setting
> 
> Scenarios would be, for morning alert open super slowly not to make any noise, and right after that set it back to 100% speed. Otherwise keeping it at 10% speed all the time would make it much unusable :) Or setting it to 10% before the sleep is annoying etc. :)

Will be awesome if this will be supported by this integration or the official one as it's exactly what was missing in my case to make it 100% perfect curtains :) 

Thanks! Although I see that their Open API doc is missing info on how to achieve that, I guess it's possible to intercept somehow and see what exact parameters are being sent to the server or just ask them through the mail :) Unfortunately being a developer I completely have no clue about Python to contribute :) Hopefully, it will be a quick addition and soon it will be there in HA  :)

**Comment by ualex73** [comment]
Sorry voor de late reply, maar ik de publieke API lijkt hier geen call voor te hebben. Maar ik vraag het voor de zekerheid na bij het support team van slide.store.

**Comment by ualex73** [comment]
@RIP21  i checked with slide support, but this option is not possible via the API. You can use the Slide App to configure this (same applies for local API, you need to switch back to the cloud to configure it).

**Comment by ualex73** [comment]
The Cloud API is closing and the local API still does not have this option (and will never get it either). So you need to use the new local App to configure this with your slide.

**Comment by RIP21** [comment]
@ualex73 am I right that this integration can work with local API just fine, so once Slide Cloud is closed down we still will be able to use it in HA just fine?

**Comment by ualex73** [comment]
Yes, the local api will work with this integration.

**Comment by RIP21** [comment]
Now on local mode and it seems like speed changing doesn't work for local mode. Does it work for you? Nor does this integration now supports it maybe?
