### ISSUE TITLE
Slide overview call doesn't update correctly. so slide displays a wrong state. added own line of code to use the "get_slide_position" call

### ISSUE THREAD

**Issue by DarrenSanders123** [ualex73/slide#5]
When using the call "slide_overview" the postion are out of date when changes it takes a few min for that to update.
added this code to fix the issue and use the slide info api call to get the correct position

```python
if "pos" in slide["device_info"]:
                slidenew["pos"] = await hass.data[DOMAIN][API_CLOUD].slide_get_position(slide["id"])
                _LOGGER.debug(slidenew["pos"])
                slidenew["online"] = True
```

**Comment by DarrenSanders123** [comment]
kan ook in Nederlands reageren :)

**Comment by ualex73** [comment]
I think we can close this one, the Cloud API will be soon gone. If you experience the same with the local API, please raise it again!
