### ISSUE TITLE
feature request: service for current position/state

### ISSUE THREAD

**Issue by olafvs** [ualex73/slide#6]
If I would have a service to get he current position / state of slide I would be able to request it just in time before I would operate my slide. Based on the outcome of the get I would be able to take appropriate action.

What I have to do now is set the update interval very low. But this causes an insane amount of network requests just to get the right position.

My use case: I have a wall dimmer for my lights which I also use to control my curtains. Using the upper button will open my curtains and using the lower button will close them. I would like to be able to stop them whem they are either opening or closing, but to do this I need the current state.

**Comment by sonar98** [comment]
@ualex73 I would really like to be able to get the current position of my slides too.

**Comment by ualex73** [comment]
This is possible if you switch to the local API, then you can call as much as you want (e.g. every 5 seconds). The Cloud API is closing, so that will become the only option.
